---

- name: Content of /etc/machine-id
  shell: 'cat /etc/machine-id'
  register: catmachineid

- name: Renew machine id from template
  block:
  when: catmachineid.stout.find('de8d5db872044308bb261515a75adbeb') != -1
    - name: Remove machine ID
      ansible.builtin.file:
        path: /etc/machine-id
        state: absent
    - name: Create new machine id rawly
      ansible.builtin.raw: systemd-machine-id-setup

# - name: Create ansible user 'ansible' and append group 'wheel'
#   ansible.builtin.user:
#     name: ansible
#     groups: wheel
#     append: yes
#     generate_ssh_key: yes
#     ssh_key_bits: 4096
#     ssh_key_file: .ssh/id_rsa

...
