---

# - name: Remove machine ID
#   ansible.builtin.file:
#     path: /etc/machine-id
#     state: absent
#   when:

# - name: Create new machine id

- name: Create ansible user 'ansible' and append group 'wheel'
  ansible.builtin.user:
    name: ansible
    groups: wheel
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa

...
